version: '3.8'

services:
  web:
    # 服务名称
    container_name: ai_time_tree
    
    # 构建指令
    build:
      # 使用当前目录下的 Dockerfile
      context: .
      dockerfile: Dockerfile
    
    # 端口映射
    # 将我们主机的 8000 端口，映射到容器的 8000 端口
    ports:
      - "8000:8000"
      
    # 卷映射
    volumes:
      - ./data:/app/data
      
    # 环境变量 (新增)
    environment:
      # 设置容器的时区为上海（东八区），与主机保持一致
      - TZ=Asia/Shanghai
      
    # 重启策略
    restart: unless-stopped
